from __future__ import annotations

DEFAULT_CATEGORIES = [
    {"name": "Sách", "slug": "books", "description": "Sách và ấn phẩm học tập, phát triển bản thân."},
    {"name": "Dụng cụ học tập", "slug": "stationery", "description": "Bút, sổ, giấy note và dụng cụ học tập hằng ngày."},
    {"name": "Đồ chơi", "slug": "toys", "description": "Đồ chơi giáo dục và sáng tạo cho trẻ em."},
    {"name": "Gói quà", "slug": "gift-packs", "description": "Combo quà tặng theo chủ đề học tập và sinh nhật."},
    {"name": "Ba lô", "slug": "backpacks", "description": "Ba lô đi học và di chuyển ngắn ngày."},
    {"name": "Bình nước", "slug": "water-bottles", "description": "Bình nước giữ nhiệt và thể thao cho ngày học dài."},
    {"name": "Đồ điện tử học tập", "slug": "study-tech", "description": "Thiết bị hỗ trợ học tập như máy tính và đèn học."},
    {"name": "Mỹ thuật", "slug": "art-supplies", "description": "Dụng cụ vẽ, tô màu và thủ công sáng tạo."},
    {"name": "Đồ trang trí bàn học", "slug": "desk-decor", "description": "Phụ kiện giúp góc học tập gọn gàng và truyền cảm hứng."},
    {"name": "Đồ lưu niệm", "slug": "souvenirs", "description": "Quà tặng và vật phẩm dễ thương để sưu tầm."},
]

DEFAULT_PRODUCT_TYPES = [
    {"name": "Book", "slug": "book", "description": "Printed books and learning publications."},
    {"name": "Stationery", "slug": "stationery", "description": "School and office stationery."},
    {"name": "Toy", "slug": "toy", "description": "Educational and creative toys."},
    {"name": "Gift Pack", "slug": "gift-pack", "description": "Curated gift bundles."},
    {"name": "Backpack", "slug": "backpack", "description": "Backpacks and carrying bags."},
    {"name": "Bottle", "slug": "bottle", "description": "Reusable bottles and tumblers."},
    {"name": "Study Tech", "slug": "study-tech", "description": "Study-support electronics and devices."},
    {"name": "Art Supply", "slug": "art-supply", "description": "Art and craft supplies."},
    {"name": "Desk Decor", "slug": "desk-decor", "description": "Desk accessories and decor."},
    {"name": "Souvenir", "slug": "souvenir", "description": "Souvenirs and collectible accessories."},
]

DEFAULT_PRODUCTS = [
    {
        "name": "Atomic Habits",
        "sku": "BOOK-ATOMIC-HABITS",
        "price": 119000,
        "stock_quantity": 150,
        "category_slug": "books",
        "product_type_slug": "book",
        "description": "Sách self-help tiếng Anh về xây dựng thói quen bền vững.",
        "attributes": {"language": "en", "genre": "Self-Help", "author": "James Clear"},
    },
    {
        "name": "Sổ tay Campus B5",
        "sku": "STA-CAMPUS-B5",
        "price": 45000,
        "stock_quantity": 300,
        "category_slug": "stationery",
        "product_type_slug": "stationery",
        "description": "Sổ tay giấy mịn phù hợp ghi chép hằng ngày và học nhóm.",
        "attributes": {"size": "B5", "pages": 120},
    },
    {
        "name": "Lego Creative Box",
        "sku": "TOY-LEGO-CREATIVE",
        "price": 399000,
        "stock_quantity": 80,
        "category_slug": "toys",
        "product_type_slug": "toy",
        "description": "Bộ LEGO sáng tạo giúp trẻ phát triển tư duy và phối màu.",
        "attributes": {"age_group": "6+", "pieces": 250},
    },
    {
        "name": "Gói quà Back To School",
        "sku": "GIFT-BTS-01",
        "price": 199000,
        "stock_quantity": 120,
        "category_slug": "gift-packs",
        "product_type_slug": "gift-pack",
        "description": "Combo quà tặng gồm sổ, bút, sticker cho mùa tựu trường.",
        "attributes": {"occasion": "back_to_school", "items": 5},
    },
    {
        "name": "Ba lô Miti Active",
        "sku": "BAG-MITI-ACTIVE",
        "price": 349000,
        "stock_quantity": 95,
        "category_slug": "backpacks",
        "product_type_slug": "backpack",
        "description": "Ba lô chống thấm nhẹ với nhiều ngăn cho học sinh, sinh viên.",
        "attributes": {"capacity": "20L", "color": "navy"},
    },
    {
        "name": "Bình giữ nhiệt LocknLock 500ml",
        "sku": "BOT-LOCK-500",
        "price": 229000,
        "stock_quantity": 140,
        "category_slug": "water-bottles",
        "product_type_slug": "bottle",
        "description": "Bình inox giữ nhiệt phù hợp mang theo khi đi học hoặc đi làm.",
        "attributes": {"volume": "500ml", "material": "stainless_steel"},
    },
    {
        "name": "Máy tính Casio FX-580VN X",
        "sku": "TECH-CASIO-580VNX",
        "price": 715000,
        "stock_quantity": 60,
        "category_slug": "study-tech",
        "product_type_slug": "study-tech",
        "description": "Máy tính khoa học dành cho học sinh THPT và sinh viên khối kỹ thuật.",
        "attributes": {"battery": "AAA", "exam_support": "high_school"},
    },
    {
        "name": "Bộ chì màu Faber-Castell 24 màu",
        "sku": "ART-FABER-24",
        "price": 189000,
        "stock_quantity": 110,
        "category_slug": "art-supplies",
        "product_type_slug": "art-supply",
        "description": "Bộ chì màu chất lượng cao dành cho học sinh yêu thích mỹ thuật.",
        "attributes": {"colors": 24, "target": "students"},
    },
    {
        "name": "Đèn bàn Minihome Focus",
        "sku": "DECOR-MINI-LAMP",
        "price": 259000,
        "stock_quantity": 70,
        "category_slug": "desk-decor",
        "product_type_slug": "desk-decor",
        "description": "Đèn bàn LED với ba chế độ sáng cho góc học tập hiện đại.",
        "attributes": {"light_mode": 3, "power": "USB"},
    },
    {
        "name": "Móc khóa Moji Capybara",
        "sku": "SOU-MOJI-CAPY",
        "price": 59000,
        "stock_quantity": 180,
        "category_slug": "souvenirs",
        "product_type_slug": "souvenir",
        "description": "Móc khóa plush dễ thương dùng làm quà tặng hoặc phụ kiện balo.",
        "attributes": {"theme": "capybara", "material": "plush"},
    },
]
